blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/solidtime-io/solidtime/discussions/new?category=feature-requests
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/solidtime-io/solidtime/discussions/new?category=general
    about: Ask the community for help
